### ISSUE TITLE
Improve log inspection in modifyvnode hook functional tests

### ISSUE THREAD

**Issue by monkeystate** [openpbs/openpbs#2216]
RIght now in master one of the tests is failing in pbs_hook_modifyvnode_state_changes.py. This is due to a flaw in the test source code (poor log match assumptions) and is not indicative of an underlying server problem. I am working on a fix.

Bad test, no biscuit:

2021-01-23 15:42:59,305 INFO     ======================================================================
2021-01-23 15:42:59,305 INFO     FAILED: test_hook_state_changes_00 (tests.functional.pbs_hook_modifyvnode_state_changes.TestPbsModifyvnodeStateChanges)

2021-01-23 15:42:59,305 INFO     ___m_oo_m___
2021-01-23 15:42:59,305 INFO     Traceback (most recent call last):
  File "/opt/ptl/tests/functional/pbs_hook_modifyvnode_state_changes.py", line 275, in test_hook_state_changes_00
    starttime=start_time)
  File "/opt/ptl/lib/python3.6/site-packages/ptl/lib/ptl_server.py", line 577, in log_match
    level=level, existence=existence)
  File "/opt/ptl/lib/python3.6/site-packages/ptl/lib/ptl_service.py", line 1141, in _log_match
    raise PtlLogMatchError(rc=1, rv=False, msg=_msg)
ptl.lib.ptl_error.PtlLogMatchError: rc=1, rv=False, msg=server pbsdev-centos7-mky18-server log match: searching for "v.state_hex=0x1 v_o.state_hex=0x0" - with existence - attempt 180

2021-01-23 15:42:59,305 INFO     ================================================================================
failed: test_hook_state_changes_00 (tests.functional.pbs_hook_modifyvnode_state_changes.TestPbsModifyvnodeStateChanges)
Test cases with failures: TestPbsModifyvnodeStateChanges.test_hook_state_changes_00
Test suites with failures: TestPbsModifyvnodeStateChanges
run: 1, succeeded: 0, failed: 1, errors: 0, skipped: 0, timedout: 0
Tests run in 0:02:11.085620
2021-01-23 15:42:59,305 INFO     Cleaning up temporary files
2021-01-23 15:42:59,305 INFO     Cleaning up /var/tmp dir
2021-01-23 15:42:59,306 INFO     Cleaning up /tmp dir

real	2m11.448s
user	0m10.493s
sys	0m3.317s
[01/23 15:42:59] pbsdev@pbsdev-centos7-mky18-server:~ 62%

**Comment by monkeystate** [comment]
Issue resolved by merge of https://github.com/openpbs/openpbs/pull/2242
